
name: Compile Latex

on: [push, pull_request]
    
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: SPM.tex
          working_directory: man
          latexmk_use_xelatex: true

      - name: Release
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: SPM.pdf
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}